# Generated by Django 4.1.5 on 2023-01-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_roles_user_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
