from groups.serializers.branch import BranchModelSerializer, BranchListModelSerializer
from groups.serializers.group import GroupListModelSerializer, GroupAddStudentModelSerializer
from groups.serializers.room import RoomListModelSerializer, RoomCreateModelSerializer
from groups.serializers.serializers import CompanyModelSerializer, HolidayCreateModelSerializer, \
    HolidayListModelSerializer, RoleModelSerializer, HomeModelSerializer
