from groups.serializers.branch import BranchModelSerializer, BranchListModelSerializer
from groups.serializers.course import CourseListModelSerializer, CourseCreateModelSerializer
from groups.serializers.group import GroupListModelSerializer
from groups.serializers.holiday import HolidayListModelSerializer, HolidayCreateModelSerializer
from groups.serializers.room import RoomListModelSerializer, RoomCreateModelSerializer
from groups.serializers.serializers import CompanyModelSerializer, \
    RoleModelSerializer, HomeModelSerializer
